version     = "2.0.9"
author      = "flatbuffers"
description = "Flatbuffers runtime implementation; compatible with files generated by flatc, but not compatible with Google's `flatbuffers` package."
license     = "Apache 2.0"
srcDir      = "src"

requires "nim >= 1.4.0"
